---
schemas:
  - schemas

menus:
  - menus

objects:
  - objects

python_transforms:
  - name: switch_hostname
    file_path: transforms/python/switch_hostname.py
    class_name: SwitchHostnameTransform
    convert_query_response: true
  - name: ios_xe_switch_config
    file_path: transforms/python/ios_xe_switch_config.py
    class_name: IosXeSwitchConfigTransform

jinja2_transforms:
  - name: switch_hostname
    description: "Transform the switch hostname"
    query: "dcim_switch_names"
    template_path: "transforms/jinja/switch_hostname.j2"
  - name: switch_interfaces
    description: "Transform the switch interfaces"
    query: "dcim_switch_interfaces"
    template_path: "transforms/jinja/switch_interfaces.j2"

queries:
  - name: dcim_switch_names
    file_path: queries/dcim_switch_names.gql
  - name: dcim_switch_interfaces
    file_path: queries/dcim_switch_interfaces.gql
  - name: ipam_ipaddress
    file_path: queries/ipam_ipaddress.gql
  - name: cml_lab_topology
    file_path: queries/cml_lab_topology.gql
  - name: dcim_switch_full_config
    file_path: queries/dcim_switch_full_config.gql
  - name: dcim_switch_ios_xe_config
    file_path: queries/dcim_switch_ios_xe_config.gql