---
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: DcimOperatingSystem
  data:
    - name: IOS-XE
      description: Cisco IOS XE Operating System
      vendor: Cisco
      terraform_provider: CiscoDevNet/iosxe
