---
# DcimPhysicalInterface: Physische Ports gemäß docs/05_verteilung.md (5.4 Trunk, 5.5 Access)
# connected_endpoint wird in 08_physical_interface_connections.yml gesetzt (nach diesem Load)
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: DcimPhysicalInterface
  data:
    # ==================== CORE BONN (SW-BN-CORE-01) ====================
    - name: Gi0/1
      device: SW-BN-CORE-01
      description: Inter-Site Link (P2P) to SW-KN-CORE-01
      l2_mode: routed
    - name: Gi0/2
      device: SW-BN-CORE-01
      description: Trunk to SW-BN-DIST-01 Gi0/2
      l2_mode: trunk
      tagged_vlans:
        - [Management, "10"]
        - [Users, "100"]
        - [Printers, "120"]
        - [Servers, "130"]
    - name: Gi0/3
      device: SW-BN-CORE-01
      description: Trunk to SW-BN-DIST-02 Gi0/2
      l2_mode: trunk
      tagged_vlans:
        - [Management, "10"]
        - [Users, "100"]
        - [Printers, "120"]
        - [Servers, "130"]

    # ==================== CORE KÖLN (SW-KN-CORE-01) ====================
    - name: Gi0/1
      device: SW-KN-CORE-01
      description: Inter-Site Link (P2P) to SW-BN-CORE-01
      l2_mode: routed
    - name: Gi0/2
      device: SW-KN-CORE-01
      description: Trunk to SW-KN-DIST-01 Gi0/2
      l2_mode: trunk
      tagged_vlans:
        - [Management, "10"]
        - [Users, "100"]
        - [Printers, "120"]
        - [Servers, "130"]
    - name: Gi0/3
      device: SW-KN-CORE-01
      description: Trunk to SW-KN-DIST-02 Gi0/2
      l2_mode: trunk
      tagged_vlans:
        - [Management, "10"]
        - [Users, "100"]
        - [Printers, "120"]
        - [Servers, "130"]
    - name: Gi0/4
      device: SW-KN-CORE-01
      description: Access – Production Server Köln (Server-KN-01)
      l2_mode: access
      untagged_vlan: [Servers, "130"]

    # ==================== DISTRIBUTION BONN ====================
    - name: Gi0/1
      device: SW-BN-DIST-01
      description: Trunk to SW-BN-DIST-02 Gi0/1
      l2_mode: trunk
      tagged_vlans:
        - [Management, "10"]
        - [Users, "100"]
        - [Printers, "120"]
        - [Servers, "130"]
    - name: Gi0/2
      device: SW-BN-DIST-01
      description: Trunk to SW-BN-CORE-01 Gi0/2
      l2_mode: trunk
      tagged_vlans:
        - [Management, "10"]
        - [Users, "100"]
        - [Printers, "120"]
        - [Servers, "130"]
    - name: Gi0/4
      device: SW-BN-DIST-01
      description: Trunk to SW-BN-01 Gi0/1
      l2_mode: trunk
      tagged_vlans:
        - [Management, "10"]
        - [Users, "100"]
        - [Printers, "120"]
        - [Servers, "130"]
    - name: Gi0/5
      device: SW-BN-DIST-01
      description: Trunk to SW-BN-02 Gi0/1
      l2_mode: trunk
      tagged_vlans:
        - [Management, "10"]
        - [Users, "100"]
        - [Printers, "120"]
        - [Servers, "130"]

    - name: Gi0/1
      device: SW-BN-DIST-02
      description: Trunk to SW-BN-DIST-01 Gi0/1
      l2_mode: trunk
      tagged_vlans:
        - [Management, "10"]
        - [Users, "100"]
        - [Printers, "120"]
        - [Servers, "130"]
    - name: Gi0/2
      device: SW-BN-DIST-02
      description: Trunk to SW-BN-CORE-01 Gi0/3
      l2_mode: trunk
      tagged_vlans:
        - [Management, "10"]
        - [Users, "100"]
        - [Printers, "120"]
        - [Servers, "130"]
    - name: Gi0/4
      device: SW-BN-DIST-02
      description: Trunk to SW-BN-01 Gi0/2
      l2_mode: trunk
      tagged_vlans:
        - [Management, "10"]
        - [Users, "100"]
        - [Printers, "120"]
        - [Servers, "130"]
    - name: Gi0/5
      device: SW-BN-DIST-02
      description: Trunk to SW-BN-02 Gi0/2
      l2_mode: trunk
      tagged_vlans:
        - [Management, "10"]
        - [Users, "100"]
        - [Printers, "120"]
        - [Servers, "130"]

    # ==================== DISTRIBUTION KÖLN ====================
    - name: Gi0/1
      device: SW-KN-DIST-01
      description: Trunk to SW-KN-DIST-02 Gi0/1
      l2_mode: trunk
      tagged_vlans:
        - [Management, "10"]
        - [Users, "100"]
        - [Printers, "120"]
        - [Servers, "130"]
    - name: Gi0/2
      device: SW-KN-DIST-01
      description: Trunk to SW-KN-CORE-01 Gi0/2
      l2_mode: trunk
      tagged_vlans:
        - [Management, "10"]
        - [Users, "100"]
        - [Printers, "120"]
        - [Servers, "130"]
    - name: Gi0/4
      device: SW-KN-DIST-01
      description: Trunk to SW-KN-01 Gi0/1
      l2_mode: trunk
      tagged_vlans:
        - [Management, "10"]
        - [Users, "100"]
        - [Printers, "120"]
        - [Servers, "130"]
    - name: Gi0/5
      device: SW-KN-DIST-01
      description: Trunk to SW-KN-02 Gi0/1
      l2_mode: trunk
      tagged_vlans:
        - [Management, "10"]
        - [Users, "100"]
        - [Printers, "120"]
        - [Servers, "130"]
    - name: Gi0/6
      device: SW-KN-DIST-01
      description: Trunk to SW-KN-03 Gi0/1
      l2_mode: trunk
      tagged_vlans:
        - [Management, "10"]
        - [Users, "100"]
        - [Printers, "120"]
        - [Servers, "130"]

    - name: Gi0/1
      device: SW-KN-DIST-02
      description: Trunk to SW-KN-DIST-01 Gi0/1
      l2_mode: trunk
      tagged_vlans:
        - [Management, "10"]
        - [Users, "100"]
        - [Printers, "120"]
        - [Servers, "130"]
    - name: Gi0/2
      device: SW-KN-DIST-02
      description: Trunk to SW-KN-CORE-01 Gi0/3
      l2_mode: trunk
      tagged_vlans:
        - [Management, "10"]
        - [Users, "100"]
        - [Printers, "120"]
        - [Servers, "130"]
    - name: Gi0/4
      device: SW-KN-DIST-02
      description: Trunk to SW-KN-01 Gi0/2
      l2_mode: trunk
      tagged_vlans:
        - [Management, "10"]
        - [Users, "100"]
        - [Printers, "120"]
        - [Servers, "130"]
    - name: Gi0/5
      device: SW-KN-DIST-02
      description: Trunk to SW-KN-02 Gi0/2
      l2_mode: trunk
      tagged_vlans:
        - [Management, "10"]
        - [Users, "100"]
        - [Printers, "120"]
        - [Servers, "130"]
    - name: Gi0/6
      device: SW-KN-DIST-02
      description: Trunk to SW-KN-03 Gi0/2
      l2_mode: trunk
      tagged_vlans:
        - [Management, "10"]
        - [Users, "100"]
        - [Printers, "120"]
        - [Servers, "130"]

    # ==================== ACCESS BONN ====================
    - name: Gi0/1
      device: SW-BN-01
      description: Trunk to SW-BN-DIST-01 Gi0/4
      l2_mode: trunk
      tagged_vlans:
        - [Management, "10"]
        - [Users, "100"]
        - [Printers, "120"]
        - [Servers, "130"]
    - name: Gi0/2
      device: SW-BN-01
      description: Trunk to SW-BN-DIST-02 Gi0/4
      l2_mode: trunk
      tagged_vlans:
        - [Management, "10"]
        - [Users, "100"]
        - [Printers, "120"]
        - [Servers, "130"]
    - name: Gi0/3
      device: SW-BN-01
      description: Access – PC-BN-01
      l2_mode: access
      untagged_vlan: [Users, "100"]
    - name: Gi0/4
      device: SW-BN-01
      description: Access – PC-BN-02
      l2_mode: access
      untagged_vlan: [Users, "100"]

    - name: Gi0/1
      device: SW-BN-02
      description: Trunk to SW-BN-DIST-01 Gi0/5
      l2_mode: trunk
      tagged_vlans:
        - [Management, "10"]
        - [Users, "100"]
        - [Printers, "120"]
        - [Servers, "130"]
    - name: Gi0/2
      device: SW-BN-02
      description: Trunk to SW-BN-DIST-02 Gi0/5
      l2_mode: trunk
      tagged_vlans:
        - [Management, "10"]
        - [Users, "100"]
        - [Printers, "120"]
        - [Servers, "130"]
    - name: Gi0/4
      device: SW-BN-02
      description: Access – Drucker-BN-01
      l2_mode: access
      untagged_vlan: [Printers, "120"]

    # ==================== ACCESS KÖLN ====================
    - name: Gi0/1
      device: SW-KN-01
      description: Trunk to SW-KN-DIST-01 Gi0/4
      l2_mode: trunk
      tagged_vlans:
        - [Management, "10"]
        - [Users, "100"]
        - [Printers, "120"]
        - [Servers, "130"]
    - name: Gi0/2
      device: SW-KN-01
      description: Trunk to SW-KN-DIST-02 Gi0/4
      l2_mode: trunk
      tagged_vlans:
        - [Management, "10"]
        - [Users, "100"]
        - [Printers, "120"]
        - [Servers, "130"]
    - name: Gi0/3
      device: SW-KN-01
      description: Access – PC-KN-01
      l2_mode: access
      untagged_vlan: [Users, "100"]
    - name: Gi0/4
      device: SW-KN-01
      description: Access – PC-KN-02
      l2_mode: access
      untagged_vlan: [Users, "100"]

    - name: Gi0/1
      device: SW-KN-02
      description: Trunk to SW-KN-DIST-01 Gi0/5
      l2_mode: trunk
      tagged_vlans:
        - [Management, "10"]
        - [Users, "100"]
        - [Printers, "120"]
        - [Servers, "130"]
    - name: Gi0/2
      device: SW-KN-02
      description: Trunk to SW-KN-DIST-02 Gi0/5
      l2_mode: trunk
      tagged_vlans:
        - [Management, "10"]
        - [Users, "100"]
        - [Printers, "120"]
        - [Servers, "130"]
    - name: Gi0/3
      device: SW-KN-02
      description: Access – PC-KN-03
      l2_mode: access
      untagged_vlan: [Users, "100"]

    - name: Gi0/1
      device: SW-KN-03
      description: Trunk to SW-KN-DIST-01 Gi0/6
      l2_mode: trunk
      tagged_vlans:
        - [Management, "10"]
        - [Users, "100"]
        - [Printers, "120"]
        - [Servers, "130"]
    - name: Gi0/2
      device: SW-KN-03
      description: Trunk to SW-KN-DIST-02 Gi0/6
      l2_mode: trunk
      tagged_vlans:
        - [Management, "10"]
        - [Users, "100"]
        - [Printers, "120"]
        - [Servers, "130"]
    - name: Gi0/3
      device: SW-KN-03
      description: Access – Drucker-KN-01
      l2_mode: access
      untagged_vlan: [Printers, "120"]
